externalAccess:
  enabled: true

  controller:
    service:
      type: NodePort
      # We need three ports becuase the Bitnami chart also creates three controller by default. Using only one controller did not work for me.
      nodePorts:
        - 31090
        - 32091
        - 32092

sasl:
  client:
    users: 
      - admin
    passwords: 
      - admin
  