ingress:
    enabled: true
    annotations:
        kubernetes.io/ingress.class: "traefik-private"
        traefik.ingress.kubernetes.io/router.middlewares: default-strip-mynginx-prefix@kubernetescrd
    hostname: localhost
    path: "/mynginx"