ingress:
    enabled: true
    annotations:
        traefik.ingress.kubernetes.io/router.middlewares: default-strip-mynginx-prefix@kubernetescrd
    ingressClassName: "traefik"
    hostname: localhost
    path: "/mynginx"