#
# Each ingress configured with ingress-class=traefik will be handled by this traefik
#

#
# Configure as node port for local kind environment
#
service:
  type: NodePort

#
# Configure k8s node ports. They are also used in kind-with-local-registry.config.yaml
# Also allow HTTP access to traefik dashboard
#
ports:
  traefik:
    nodePort: 32090
    expose:
         default: true
  web:
    nodePort: 32080
  websecure:
    nodePort: 32443

#
# Enable traefik dashboard
#
ingressRoute:
  dashboard:
    enabled: true

#
# URL rewriting for nginx endpoint from '/mynginx' to '/'
#
extraObjects:
  - apiVersion: traefik.io/v1alpha1
    kind: Middleware
    metadata:
      name: strip-mynginx-prefix
      namespace: default
    spec:
      stripPrefix:
        prefixes:
          - "/mynginx"